name: Test

on: [push]

jobs:
  lint_and_test:
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Install Go dependencies
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.1
          go install github.com/axw/gocov/gocov@latest
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install github.com/ory/go-acc@latest
          go get -u github.com/client9/misspell/cmd/misspell
          go get -u github.com/gordonklaus/ineffassign
          go get github.com/stretchr/testify/assert@v1.7.0
          go get github.com/ory/go-acc
          go get google.golang.org/grpc@v1.38.0
          go get google.golang.org/grpc/balancer/grpclb@v1.38.0
          go get google.golang.org/api/support/bundler@v0.48.0
          go get contrib.go.opencensus.io/exporter/stackdriver@v0.13.6
          go get github.com/savannahghi/firebasetools

      - name: Run lint and test
        run: |
          gosec ./...
          go-acc -o coverage.txt --ignore generated,cmd  ./... -- -timeout 60m
          grep -v "generated.go" coverage.txt > coverage.out
          go tool cover -html=coverage.out -o coverage.html
          gocov convert coverage.out > coverage.json
          gocov report coverage.json > coverage_report.txt
          tail coverage_report.txt
        
      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=coverage.out  -service=github